model:
  heads:
    object:
      type: TransFusionHead
      # init_cfg:
      #     type: Pretrained
      #     checkpoint: /home/bevfusion/model/resnet50/bevfusion-det.pth
      #     prefix: heads.object.
      num_proposals: 200
      auxiliary: true
      in_channels: null
      hidden_channel: 128
      num_classes: 10
      num_decoder_layers: 1
      num_heads: 8
      nms_kernel_size: 3
      ffn_channel: 256
      dropout: 0.1
      bn_momentum: 0.1
      activation: relu
      train_cfg:
        dataset: nuScenes
        point_cloud_range: ${point_cloud_range}
        grid_size: [1024, 1024, 1]
        voxel_size: ${voxel_size}
        out_size_factor: 8
        gaussian_overlap: 0.1
        min_radius: 2
        pos_weight: -1
        code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]
        assigner:
          type: HungarianAssigner3D
          iou_calculator:
            type: BboxOverlaps3D
            coordinate: lidar
          cls_cost:
            type: FocalLossCost
            gamma: 2.0
            alpha: 0.25
            weight: 0.15
          reg_cost:
            type: BBoxBEVL1Cost
            weight: 0.25
          iou_cost:
            type: IoU3DCost
            weight: 0.25
      test_cfg:
        dataset: nuScenes
        grid_size: [1024, 1024, 1]
        out_size_factor: 8
        voxel_size: ${voxel_size[:2]}
        pc_range: ${point_cloud_range[:2]}
        nms_type: null
      common_heads:
        center: [2, 2]
        height: [1, 2]
        dim: [3, 2]
        rot: [2, 2]
        vel: [2, 2]
      bbox_coder:
        type: TransFusionBBoxCoder
        pc_range: ${point_cloud_range[:2]}
        post_center_range: [-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]
        score_threshold: 0.0
        out_size_factor: 8
        voxel_size: ${voxel_size[:2]}
        code_size: 10
      loss_cls: 
        type: FocalLoss
        use_sigmoid: true
        gamma: 2.0
        alpha: 0.25
        reduction: mean
        loss_weight: 0.8
      loss_heatmap:
        type: GaussianFocalLoss
        reduction: mean
        loss_weight: 0.8
      loss_bbox:
        type: L1Loss
        reduction: mean
        loss_weight: 0.25

    map:
      type: BEVSegmentationHead
      in_channels: 512
      # init_cfg:
      #     type: Pretrained
      #     checkpoint: /home/bevfusion/model/resnet50/bevfusion-det.pth
      #     prefix: heads.
      grid_transform:
        input_scope: [[-51.2, 51.2, 0.8], [-51.2, 51.2, 0.8]]
        output_scope: [[-50, 50, 0.5], [-50, 50, 0.5]]
      classes: ${map_classes}
      loss: focal

    planner:
      type: ImitationHead
      in_channels: 512
      out_channels: 3
      waypoint_config:
        gru_hidden_size: 64
        gru_concat_target_point: true
        pred_len: 5